package Entite;
// Generated 2018-10-08 14:54:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorieboutique generated by hbm2java
 */
public class Categorieboutique  implements java.io.Serializable {


     private short idcategorie;
     private String nomcategorie;
     private Set produitboutiques = new HashSet(0);

    public Categorieboutique() {
    }

	
    public Categorieboutique(short idcategorie) {
        this.idcategorie = idcategorie;
    }
    public Categorieboutique(short idcategorie, String nomcategorie, Set produitboutiques) {
       this.idcategorie = idcategorie;
       this.nomcategorie = nomcategorie;
       this.produitboutiques = produitboutiques;
    }
   
    public short getIdcategorie() {
        return this.idcategorie;
    }
    
    public void setIdcategorie(short idcategorie) {
        this.idcategorie = idcategorie;
    }
    public String getNomcategorie() {
        return this.nomcategorie;
    }
    
    public void setNomcategorie(String nomcategorie) {
        this.nomcategorie = nomcategorie;
    }
    public Set getProduitboutiques() {
        return this.produitboutiques;
    }
    
    public void setProduitboutiques(Set produitboutiques) {
        this.produitboutiques = produitboutiques;
    }




}


