package Entite;
// Generated 2018-10-08 14:54:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commandeboutique generated by hbm2java
 */
public class Commandeboutique  implements java.io.Serializable {


     private BigDecimal nocommande;
     private Clientboutique clientboutique;
     private Date datecommande;
     private Set ligneCommandeboutiques = new HashSet(0);

    public Commandeboutique() {
    }

	
    public Commandeboutique(BigDecimal nocommande) {
        this.nocommande = nocommande;
    }
    public Commandeboutique(BigDecimal nocommande, Clientboutique clientboutique, Date datecommande, Set ligneCommandeboutiques) {
       this.nocommande = nocommande;
       this.clientboutique = clientboutique;
       this.datecommande = datecommande;
       this.ligneCommandeboutiques = ligneCommandeboutiques;
    }
   
    public BigDecimal getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(BigDecimal nocommande) {
        this.nocommande = nocommande;
    }
    public Clientboutique getClientboutique() {
        return this.clientboutique;
    }
    
    public void setClientboutique(Clientboutique clientboutique) {
        this.clientboutique = clientboutique;
    }
    public Date getDatecommande() {
        return this.datecommande;
    }
    
    public void setDatecommande(Date datecommande) {
        this.datecommande = datecommande;
    }
    public Set getLigneCommandeboutiques() {
        return this.ligneCommandeboutiques;
    }
    
    public void setLigneCommandeboutiques(Set ligneCommandeboutiques) {
        this.ligneCommandeboutiques = ligneCommandeboutiques;
    }




}


