package Entite;
// Generated 2018-10-08 14:54:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Descritptionboutique generated by hbm2java
 */
public class Descritptionboutique  implements java.io.Serializable {


     private BigDecimal idDescription;
     private Produitboutique produitboutique;
     private String langue;

    public Descritptionboutique() {
    }

	
    public Descritptionboutique(BigDecimal idDescription, String langue) {
        this.idDescription = idDescription;
        this.langue = langue;
    }
    public Descritptionboutique(BigDecimal idDescription, Produitboutique produitboutique, String langue) {
       this.idDescription = idDescription;
       this.produitboutique = produitboutique;
       this.langue = langue;
    }
   
    public BigDecimal getIdDescription() {
        return this.idDescription;
    }
    
    public void setIdDescription(BigDecimal idDescription) {
        this.idDescription = idDescription;
    }
    public Produitboutique getProduitboutique() {
        return this.produitboutique;
    }
    
    public void setProduitboutique(Produitboutique produitboutique) {
        this.produitboutique = produitboutique;
    }
    public String getLangue() {
        return this.langue;
    }
    
    public void setLangue(String langue) {
        this.langue = langue;
    }




}


