package Entite;
// Generated 2018-10-08 14:54:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factureboutique generated by hbm2java
 */
public class Factureboutique  implements java.io.Serializable {


     private BigDecimal idfacture;
     private BigDecimal prixht;
     private BigDecimal prixttc;
     private Date datefacturation;
     private Set produitboutiques = new HashSet(0);
     private Set paiementboutiques = new HashSet(0);

    public Factureboutique() {
    }

	
    public Factureboutique(BigDecimal idfacture, Date datefacturation) {
        this.idfacture = idfacture;
        this.datefacturation = datefacturation;
    }
    public Factureboutique(BigDecimal idfacture, BigDecimal prixht, BigDecimal prixttc, Date datefacturation, Set produitboutiques, Set paiementboutiques) {
       this.idfacture = idfacture;
       this.prixht = prixht;
       this.prixttc = prixttc;
       this.datefacturation = datefacturation;
       this.produitboutiques = produitboutiques;
       this.paiementboutiques = paiementboutiques;
    }
   
    public BigDecimal getIdfacture() {
        return this.idfacture;
    }
    
    public void setIdfacture(BigDecimal idfacture) {
        this.idfacture = idfacture;
    }
    public BigDecimal getPrixht() {
        return this.prixht;
    }
    
    public void setPrixht(BigDecimal prixht) {
        this.prixht = prixht;
    }
    public BigDecimal getPrixttc() {
        return this.prixttc;
    }
    
    public void setPrixttc(BigDecimal prixttc) {
        this.prixttc = prixttc;
    }
    public Date getDatefacturation() {
        return this.datefacturation;
    }
    
    public void setDatefacturation(Date datefacturation) {
        this.datefacturation = datefacturation;
    }
    public Set getProduitboutiques() {
        return this.produitboutiques;
    }
    
    public void setProduitboutiques(Set produitboutiques) {
        this.produitboutiques = produitboutiques;
    }
    public Set getPaiementboutiques() {
        return this.paiementboutiques;
    }
    
    public void setPaiementboutiques(Set paiementboutiques) {
        this.paiementboutiques = paiementboutiques;
    }




}


