package Entite;
// Generated 2018-10-08 14:54:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tailleboutique generated by hbm2java
 */
public class Tailleboutique  implements java.io.Serializable {


     private BigDecimal idtaille;
     private Produitboutique produitboutique;
     private String taille;

    public Tailleboutique() {
    }

	
    public Tailleboutique(BigDecimal idtaille, Produitboutique produitboutique) {
        this.idtaille = idtaille;
        this.produitboutique = produitboutique;
    }
    public Tailleboutique(BigDecimal idtaille, Produitboutique produitboutique, String taille) {
       this.idtaille = idtaille;
       this.produitboutique = produitboutique;
       this.taille = taille;
    }
   
    public BigDecimal getIdtaille() {
        return this.idtaille;
    }
    
    public void setIdtaille(BigDecimal idtaille) {
        this.idtaille = idtaille;
    }
    public Produitboutique getProduitboutique() {
        return this.produitboutique;
    }
    
    public void setProduitboutique(Produitboutique produitboutique) {
        this.produitboutique = produitboutique;
    }
    public String getTaille() {
        return this.taille;
    }
    
    public void setTaille(String taille) {
        this.taille = taille;
    }




}


