DROP TABLE DESCRITPTIONBOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE TAILLEBOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE COLORBOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE PAIEMENTBOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE CLIENTBOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE COMMANDEBOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE LIGNE_COMMANDEBOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE CATEGORIEBOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE PRODUITBOUTIQUE CASCADE CONSTRAINTS;
DROP TABLE MARQUEBOUTIQUE CASCADE CONSTRAINTS;

CREATE TABLE CLIENT1BOUTIQUE(
IDCLIENT NUMBER(20) CONSTRAINT PK_CLIENT PRIMARY KEY ,
NOMCLIENT VARCHAR(30) CONSTRAINT NN_NOMCLIENT NOT NULL,
PRENOMCLIENT VARCHAR(40) CONSTRAINT NN_PRENOMCLIENT NOT NULL,
COURIEL VARCHAR(40) CONSTRAINT NNU_COURRIEL NOT NULL UNIQUE,
MOTDEPASSE VARCHAR(40) CONSTRAINT NN_MOTDEPASSE NOT NULL,
TELEPHONECLIENT VARCHAR(15),
NOCIVIQUE VARCHAR (10),
NOAPP  VARCHAR(3),
NOMRUE VARCHAR(30),
VILLE VARCHAR(20),
PROVINCE VARCHAR(20),
PAYS VARCHAR(20)
);


CREATE  TABLE COMMANDEBOUTIQUE
( 
NOCOMMANDE NUMBER(30) PRIMARY KEY,
DATECOMMANDE DATE,
IDCLIENT NUMBER(20),
CONSTRAINT FK_COMMANDE FOREIGN KEY (IDCLIENT) REFERENCES CLIENT(IDCLIENT),
);

CREATE TABLE CATEGORIEBOUTIQUE(
IDCATEGORIE NUMBER(3) CONSTRAINT PK_CATEGORIE PRIMARY KEY,
NOMCATEGORIE VARCHAR(30)
);

CREATE TABLE MARQUEBOUTIQUE (
IDMARQUE NUMBER(2) PRIMARY KEY,
NOM VARCHAR(50)
);



CREATE TABLE PRODUITBOUTIQUE(
IDPRODUIT  NUMBER(20) CONSTRAINT PK_PRODUIT PRIMARY KEY,
IDMARQUE NUMBER(2),
NOMPRODUIT VARCHAR(50),
DESCRIPTION VARCHAR(500),
PRIX NUMBER(6,2),
FORMATPRO VARCHAR(10),
QUANTITEENSTOCK NUMBER(6),
image varchar(200),
IDCATEGORIE NUMBER(3),
CONSTRAINT FK_IDCATEGORIE FOREIGN KEY(IDCATEGORIE) REFERENCES CATEGORIE(IDCATEGORIE),
CONSTRAINT FK_IDMARQUE FOREIGN KEY(IDMARQUE) REFERENCES MARQUE(IDMARQUE)
);

CREATE TABLE DESCRITPTIONBOUTIQUE(
ID_DESCRIPTION NUMBER(20) CONSTRAINT PK_DESCRIPTION PRIMARY KEY,
LANGUE VARCHAR(500) NOT NULL,
PRODUIT NUMBER(20),
CONSTRAINT FK_DESC_PROD FOREIGN KEY (PRODUIT) REFERENCES PRODUIT(IDPRODUIT)
);

CREATE TABLE COLORBOUTIQUE(
IDCOLOR NUMBER(20) CONSTRAINT PK_COLOR PRIMARY KEY,
COLOR VARCHAR(20),
PRODUIT NUMBER(20) NOT NULL,
CONSTRAINT FK_PRODUIT FOREIGN KEY (PRODUIT) REFERENCES PRODUIT(IDPRODUIT)
);

CREATE TABLE TAILLEBOUTIQUE(
IDTAILLE NUMBER(20) CONSTRAINT PK_TAILLE PRIMARY KEY,
TAILLE VARCHAR(1),
PRODUIT NUMBER(20) NOT NULL,
CONSTRAINT FK_PRODUIT FOREIGN KEY (PRODUIT) REFERENCES PRODUIT(IDPRODUIT)
);

CREATE TABLE LIGNE_COMMANDEBOUTIQUE (
NOCOMMANDE NUMBER(30), 
IDPRODUIT NUMBER(20),
QUANTITE NUMBER(5),
CONSTRAINT FK_NOCOMMANDE  FOREIGN KEY(NOCOMMANDE) REFERENCES COMMANDE(NOCOMMANDE),
CONSTRAINT FK_IDPRODUIT FOREIGN KEY(IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT),
CONSTRAINT PK_LIGNE_COMMANDE PRIMARY KEY (NOCOMMANDE,IDPRODUIT)
);


CREATE TABLE FACTUREBOUTIQUE(
IDFACTURE NUMBER(30),
NOCOMMANDE NUMBER(30),
PRIXHT NUMBER(7,2),
PRIXTTC NUMBER(7,2),
DATEFACTURATION DATE NOT NULL,
CONSTRAINT FACTURE_ID_PK PRIMARY KEY (IDFACTURE,NOCOMMANDE),
CONSTRAINT FACTURE_NOCOMMANDE_FK FOREIGN KEY (NOCOMMANDE) REFERENCES COMMANDE(NOCOMMANDE)
);

CREATE TABLE PAIEMENTBOUTIQUE(
IDPAIEMENT NUMBER(30) PRIMARY KEY,
TYPEPAIEMENT ENUM('VISA','COMPTENT','MASTERCARD','CARDCADEAU') NOT NULL,
FACTURE NUMBER(30) NOT NULL,
DATEDEPAIEMENT DATE NOT NULL,
MONTANTPAYER  NUMBER(7,2),
CONSTRAINT FK_FACTURE   FOREIGN KEY (FACTURE) REFERENCES FACTURE(IDFACTURE)
);